// Gate self-tests: the review-round budget, the convergence checker's evidence and identity
// checks, the adapter checker's write and drift guards, and the browser-walk edge cases.
// Every fixture is a disposable directory or Git repository; synthetic review reports and
// launch rows here are fixtures, not evidence that any agent ran.
// Run from the repository root: `node --test ".harness/tests/*.mjs"`.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, mkdirSync, mkdtempSync, rmSync, existsSync, realpathSync, symlinkSync, unlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { root, renderAdapters } from "../bin/check-adapters.mjs";
import { isSecuritySurface, template } from "../bin/check-redteam-convergence-receipt.mjs";

const require = createRequire(import.meta.url);
const stall = require("../lib/redteam-stall.cjs");
const { isAgentIdentity } = require("../lib/agent-identity.cjs");

function tempDir(t, prefix) {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), prefix)));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  return dir;
}
function put(dir, path, content) {
  const p = join(dir, path); mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, content);
}
function git(cwd, ...args) {
  const r = spawnSync("git", ["-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", ...args], { cwd, encoding: "utf8" });
  assert.equal(r.status, 0, r.stderr); return r.stdout.trim();
}
const node = (args, opts = {}) => spawnSync(process.execPath, args, { encoding: "utf8", ...opts });

// ---- symlink invocation -----------------------------------------------------------------------

test("adapter and task-contract CLIs still run their checks when invoked through a symlinked directory", (t) => {
  const dir = tempDir(t, "harness-symlink-");
  const install = join(dir, "real");
  for (const path of [".harness/bin/check-adapters.mjs", ".harness/manifest.json"]) put(install, path, readFileSync(join(root, path)));
  for (const [path, text] of Object.entries(renderAdapters({ codex: false }))) put(install, path, text);
  put(install, ".claude/commands/analyze.md", "drifted\n");
  const link = join(dir, "link");
  symlinkSync(install, link);
  const adapters = node([join(link, ".harness/bin/check-adapters.mjs")]);
  assert.equal(adapters.status, 1, `drift must be reported through the link: ${adapters.stdout}${adapters.stderr}`);
  assert.match(adapters.stderr, /Adapter drift: \.claude\/commands\/analyze\.md/);
  const repoLink = join(dir, "repo-link");
  symlinkSync(root, repoLink);
  put(dir, "bad.md", "# no contract\n");
  const contract = node([join(repoLink, ".harness/bin/check-task-contract.mjs"), join(dir, "bad.md")]);
  assert.equal(contract.status, 1, `an invalid contract must fail through the link: ${contract.stdout}${contract.stderr}`);
  assert.equal(JSON.parse(contract.stdout).ready, false);
});

// ---- adapter checker: stray files, traversal, symlinked targets, effort allowlist --------------

function adapterInstall(t, prefix) {
  const dir = tempDir(t, prefix);
  for (const path of [".harness/bin/check-adapters.mjs", ".harness/manifest.json"]) put(dir, path, readFileSync(join(root, path)));
  const invoke = (...args) => node([join(dir, ".harness/bin/check-adapters.mjs"), ...args]);
  return { dir, invoke };
}

test("stale generated Codex files are drift and --write removes them; the project's own skills are left alone", (t) => {
  const { dir, invoke } = adapterInstall(t, "harness-stray-");
  assert.equal(invoke("--write", "--codex").status, 0);
  assert.equal(invoke().status, 0);
  put(dir, ".codex/agents/harness-old-reviewer.toml", 'name = "harness-old-reviewer"\n');
  put(dir, ".agents/skills/deploy/SKILL.md", "---\nname: deploy\n---\nRead and follow the repository's `.harness/adapters/codex.md`, then ...\n");
  put(dir, ".agents/skills/my-own/SKILL.md", "---\nname: my-own\n---\nThe project's own skill.\n");
  const drift = invoke();
  assert.equal(drift.status, 1, drift.stdout + drift.stderr);
  assert.match(drift.stderr, /Adapter drift: \.codex\/agents\/harness-old-reviewer\.toml/);
  assert.match(drift.stderr, /Adapter drift: \.agents\/skills\/deploy\/SKILL\.md/);
  assert.doesNotMatch(drift.stderr, /Adapter drift: \.agents\/skills\/my-own/);
  assert.match(drift.stderr, /\.agents\/skills\/my-own\/SKILL\.md is not generated by the harness/);
  assert.equal(invoke("--codex-only").status, 1, "--codex-only sees stale Codex files too");
  assert.equal(invoke("--write").status, 0);
  assert.equal(existsSync(join(dir, ".codex/agents/harness-old-reviewer.toml")), false);
  assert.equal(existsSync(join(dir, ".agents/skills/deploy")), false);
  assert.equal(existsSync(join(dir, ".agents/skills/my-own/SKILL.md")), true, "never delete a file the harness did not generate");
  assert.equal(invoke().status, 0);
});

test("--write never writes outside the repository: phase names are validated and symlinked directories refused", (t) => {
  const { dir, invoke } = adapterInstall(t, "harness-traverse-");
  const outside = tempDir(t, "harness-outside-");
  const manifestPath = join(dir, ".harness/manifest.json");
  const pristine = readFileSync(manifestPath, "utf8");
  const manifest = JSON.parse(pristine);
  manifest.phases[`../../../..${outside}/escape`] = "escape";
  writeFileSync(manifestPath, JSON.stringify(manifest));
  const traversal = invoke("--write");
  assert.equal(traversal.status, 1, traversal.stdout + traversal.stderr);
  assert.match(traversal.stderr, /Invalid phase/);
  assert.equal(existsSync(join(outside, "escape.md")), false);
  writeFileSync(manifestPath, pristine);
  mkdirSync(join(dir, ".claude"), { recursive: true });
  symlinkSync(outside, join(dir, ".claude/commands"));
  const linked = invoke("--write");
  assert.equal(linked.status, 1, linked.stdout + linked.stderr);
  assert.match(linked.stderr, /Refusing to write/);
  assert.equal(existsSync(join(outside, "analyze.md")), false, "nothing lands in the symlink target");
});

test("Codex reasoning effort outside the verified list is refused", (t) => {
  for (const effort of ["ultra", "max", "bogus"]) {
    const { dir, invoke } = adapterInstall(t, "harness-effort-");
    const manifest = JSON.parse(readFileSync(join(dir, ".harness/manifest.json"), "utf8"));
    manifest.codex.agents.reviewer.model_reasoning_effort = effort;
    writeFileSync(join(dir, ".harness/manifest.json"), JSON.stringify(manifest));
    const result = invoke("--write", "--codex-only");
    assert.equal(result.status, 1, effort);
    assert.match(result.stderr, /Invalid Codex agent settings: reviewer/, effort);
  }
});

// ---- browser-walk checker edge cases ----------------------------------------------------------

test("browser-walk checker: empty folder is UNRUN; fences, near-miss headings, hidden blocked walks and empty reasons fail", (t) => {
  const dir = tempDir(t, "harness-walk-edge-");
  const script = join(root, ".harness/bin/check-browser-walk-receipts.mjs");
  mkdirSync(join(dir, "empty"));
  const empty = node([script, join(dir, "empty")]);
  assert.equal(empty.status, 3, `an empty folder is not a pass: ${empty.stdout}`);
  assert.match(empty.stdout, /UNRUN/);
  const run = (name, text) => { put(dir, name, text); return node([script, join(dir, name)]); };
  const fields = "Steps: opened the page, saved\nObserved: saved row listed after reload\n";
  const honest = "# w01-01\n\n## Verification\n\nBrowser walk: not applicable — command-line tool, no screen.\n";
  assert.equal(run("honest.md", honest).status, 0, "control: an honest declaration passes");
  const cases = {
    "fenced.md": "# w01-02\n\n## Verification\n\n```md\nBrowser walk: not applicable — example only\n```\n",
    "near-miss.md": "# w01-03\n\n## Verification notes (planned)\n\nBrowser walk: not applicable — later\n",
    "two-sections.md": `${honest}\n## Verification\n\n### Browser walk receipt\n\n${fields}Disposition: blocked — save does nothing\n`,
    "later-blocked.md": `# w01-04\n\n## Verification\n\n### Browser walk receipt\n\n${fields}Disposition: proceed\n\n### Browser walk receipt\n\n${fields}Disposition: confused — no feedback\n`,
    "dot-reason.md": "# w01-05\n\n## Verification\n\nBrowser walk: not applicable — .\n",
  };
  for (const [name, text] of Object.entries(cases)) {
    const result = run(name, text);
    assert.equal(result.status, 1, `${name}: ${result.stdout}`);
  }
});

// ---- security surface ------------------------------------------------------------------------

test("security surface is inclusion by default: only bookkeeping, runtime state and plain docs are excluded", () => {
  for (const path of [
    "middleware.ts", "prisma/schema.prisma", "supabase/migrations/001_policies.sql", "migrations/0005_drop_row_security.sql",
    "pages/api/admin.ts", "routes/admin.py", "config/cors.ts", "next.config.js", ".gitignore", "deploy/deployment-config.md",
    "infra/main.tf", ".env.example", "Dockerfile.prod", "public/logo.svg", "requirements-dev.txt", ".harness/guides/x.md",
    // A bookkeeping NAME outside the bookkeeping LOCATIONS is ordinary code.
    "src/.session-notes.ts", "src/auth/.session-notes.d/x.ts", "src/.wave-tracker.d/x.ts",
  ]) assert.equal(isSecuritySurface(path), true, path);
  for (const path of [
    "README.md", "LICENSE", "CHANGELOG.md", "docs/guide.md", "docs/diagram.png", "workspaces/demo/specs/overview.md",
    "workspaces/demo/04-validate/round-w01-1.json", "workspaces/demo/todos/completed/w01-01-x.md", ".session-notes",
    ".claude/learning/redteam-stall-state.json",
  ]) assert.equal(isSecuritySurface(path), false, path);
});

// ---- identity denylist -----------------------------------------------------------------------

test("one identity denylist refuses agent, model, role and harness names, and accepts a person's name", () => {
  for (const v of ["codex", "Codex agent", "Claude Opus", "gpt-6-sol", "gemini", "copilot", "reviewer", "security-reviewer",
    "harness-reviewer", "harness-anything", "implementer", "build-fix", "independent planning reviewer", "N/A", "user", ""]) {
    assert.equal(isAgentIdentity(v), true, v);
  }
  for (const v of ["Jane Doe", "Fixture Owner", "Wai Luen"]) assert.equal(isAgentIdentity(v), false, v);
});

test("a delivery contract approved by an agent is not ready", (t) => {
  const dir = tempDir(t, "harness-contract-identity-");
  const contract = (approved_by) => ({
    approved_by, owned_paths: ["src/x.mjs"], acceptance: [{ id: "A1", scenario: "s", verify: "v" }], interfaces: ["x()"],
    dependencies: [], boundaries: { trusted: ["t"], untrusted: ["u"], excluded: ["e"] }, integration: "real",
    test_environment: { isolation: "none", command: "node x", ordinary_failures: ["f"] }, open_questions: [],
  });
  const check = (who) => {
    put(dir, "todo.md", "# t\n\n## Delivery contract\n\n```json\n" + JSON.stringify(contract(who)) + "\n```\n");
    return node([join(root, ".harness/bin/check-task-contract.mjs"), join(dir, "todo.md")]);
  };
  assert.equal(check("Jane Doe").status, 0, "control: a person's name is accepted");
  for (const who of ["codex", "harness-todo-manager", "independent planning reviewer or user"]) {
    const result = check(who);
    assert.equal(result.status, 1, who);
    assert.match(result.stdout, /approved_by must name the person/, who);
  }
});

// ---- round budget (pure) ---------------------------------------------------------------------

const H1 = "1".repeat(40), H2 = "2".repeat(40), H3 = "3".repeat(40);
function round(n, verdicts, extra = {}) {
  const ids = extra.ids ?? ["correctness", "security"];
  const reviewers = ids.map((id, i) => ({ id, verdict: verdicts[i] ?? verdicts[0], evidence: `r${n}-${id}.md` }));
  const clean = reviewers.every((r) => r.verdict === "CLEAR");
  const notClear = reviewers.some((r) => r.verdict === "NOT_CLEAR");
  const { ids: _ids, ...rest } = extra;
  return { branch: "feat/w01", round: n, head: H1, expected_reviewers: ids, reviewers,
    root_causes: notClear ? [`key-${n}`] : [], ...rest, ...(clean ? { root_causes: [] } : {}) };
}
function play(rounds) {
  let state; const out = [];
  for (const r of rounds) { const o = stall.advanceRound(state, r); state = o.nextState; out.push(o); }
  return { state, out };
}

test("three-round cap: the third non-clear round owes the debug round, then a named human", () => {
  const { state, out } = play([1, 2, 3].map((n) => round(n, ["NOT_CLEAR"], { head: [H1, H2, H3][n - 1] })));
  assert.deepEqual(out.map((o) => o.action), ["FIX", "FIX", "DEBUG_ROUND"]);
  assert.throws(() => stall.advanceRound(state, round(4, ["NOT_CLEAR"])), (e) => e.code === "DEBUG_ROUND");
  assert.throws(() => stall.advanceRound(state, round(4, ["NOT_CLEAR"], { debug: true, replan: "d1.md" })),
    /never used on this branch/, "the debug round needs fresh lenses");
  const debug = stall.advanceRound(state, round(4, ["NOT_CLEAR"], { debug: true, replan: "d1.md", ids: ["debug-correctness"] }));
  assert.equal(debug.action, "ESCALATE_TO_HUMAN");
  const next = round(5, ["NOT_CLEAR"], { ids: ["debug-correctness"] });
  assert.throws(() => stall.advanceRound(debug.nextState, next), (e) => e.code === "ESCALATE_TO_HUMAN");
  assert.throws(() => stall.advanceRound(debug.nextState, { ...next, escalation_accepts: { acceptor: "codex", record: "a5.md" } }),
    /must be a named human/, "an agent cannot accept the escalation");
  const accepted = stall.advanceRound(debug.nextState, { ...next, escalation_accepts: { acceptor: "Jane Doe", record: "a5.md" } });
  assert.equal(accepted.nextState.roundsRecorded, 5);
});

test("recurrence fires REPLAN for a repeated root cause, even across a clean round", () => {
  const twice = play([round(1, ["NOT_CLEAR"], { root_causes: ["lost-update"] }),
    round(2, ["NOT_CLEAR"], { head: H2, root_causes: ["lost-update"] })]);
  assert.equal(twice.out[1].action, "REPLAN");
  const across = play([round(1, ["NOT_CLEAR"], { root_causes: ["lost-update"] }), round(2, ["CLEAR"], { head: H2 }),
    round(3, ["NOT_CLEAR"], { head: H3, root_causes: ["lost-update"] })]);
  assert.equal(across.state.replanRequired, true, "a clean round in between does not reset recurrence");
  const fresh = play([round(1, ["NOT_CLEAR"], { root_causes: ["lost-update"] }),
    round(2, ["NOT_CLEAR"], { head: H2, root_causes: ["other-cause"] })]);
  assert.equal(fresh.out[1].action, "FIX", "control: a new root cause does not fire");
});

test("four non-clear rounds since the last decision record require REPLAN, even on human-accepted rounds", () => {
  let { state } = play([1, 2, 3].map((n) => round(n, ["NOT_CLEAR"], { head: [H1, H2, H3][n - 1] })));
  const ids = ["debug-correctness"];
  state = stall.advanceRound(state, round(4, ["NOT_CLEAR"], { debug: true, replan: "d4.md", ids })).nextState;
  const acceptedRound = (n) => round(n, ["NOT_CLEAR"], { ids, escalation_accepts: { acceptor: "Jane Doe", record: `a${n}.md` } });
  for (const n of [5, 6]) state = stall.advanceRound(state, acceptedRound(n)).nextState;
  assert.equal(state.replanRequired, false, "three non-clear rounds since the decision record: not yet");
  state = stall.advanceRound(state, acceptedRound(7)).nextState;
  assert.equal(state.replanRequired, true, "the fourth fires");
  assert.throws(() => stall.advanceRound(state, acceptedRound(8)), (e) => e.code === "REPLAN");
});

test("partial rounds, gaps and an unchanged-head confirmation are judged exactly", () => {
  const partial = round(1, ["CLEAR"]);
  partial.reviewers = partial.reviewers.slice(0, 1);
  assert.throws(() => stall.advanceRound(undefined, partial), /partial rounds cannot count/);
  const first = stall.advanceRound(undefined, round(1, ["CLEAR"]));
  assert.throws(() => stall.advanceRound(first.nextState, round(3, ["CLEAR"])), /without gaps/);
  assert.equal(stall.advanceRound(first.nextState, round(2, ["CLEAR"])).action, "VERIFY_CONVERGENCE_RECEIPT");
  const moved = stall.advanceRound(first.nextState, round(2, ["CLEAR"], { head: H2 }));
  assert.equal(moved.action, "REVIEW", "a moved head restarts the clean count");
  const errors = play([round(1, ["ERROR"]), round(2, ["ERROR"]), round(3, ["ERROR"])]);
  assert.deepEqual(errors.out.map((o) => o.nextState.roundsRecorded), [0, 0, 1], "two free errored re-runs, the third is charged");
});

// ---- recorder CLI in a real repository -------------------------------------------------------

function recorderRepo(t) {
  const repo = tempDir(t, "harness-recorder-");
  git(repo, "init", "-q", "-b", "main");
  put(repo, ".gitignore", ".claude/learning/\n");
  git(repo, "add", "-A"); git(repo, "commit", "-qm", "base");
  git(repo, "checkout", "-qb", "feat/w01");
  const heads = [];
  for (let n = 1; n <= 4; n++) {
    put(repo, `src/v${n}.txt`, `${n}\n`);
    for (const id of ["correctness", "security"]) put(repo, `workspaces/demo/04-validate/w01-${id}-r${n}.md`, "Verdict: NOT_CLEAR\n");
    git(repo, "add", "-A"); git(repo, "commit", "-qm", `work ${n}`);
    heads.push(git(repo, "rev-parse", "HEAD"));
  }
  const record = (n, verdict, extra = {}) => {
    const file = `workspaces/demo/04-validate/round-w01-${n}.json`;
    const reviewers = ["correctness", "security"].map((id) => ({ id, verdict, evidence: `workspaces/demo/04-validate/w01-${id}-r${n}.md` }));
    put(repo, file, JSON.stringify({ branch: "feat/w01", round: n, head: heads[n - 1], expected_reviewers: ["correctness", "security"],
      reviewers, root_causes: verdict === "NOT_CLEAR" ? [`cause-${n}`] : [], ...extra }));
    return node([join(root, ".harness/bin/record-review-round.mjs"), file], { cwd: repo });
  };
  return { repo, heads, record };
}

test("recorder exit codes: refused branch/head is 1, DEBUG_ROUND is 2, VERIFY_CONVERGENCE_RECEIPT is 0", (t) => {
  const { repo, heads, record } = recorderRepo(t);
  const wrongBranch = record(1, "CLEAR", { branch: "feat/renamed" });
  assert.equal(wrongBranch.status, 1, wrongBranch.stdout);
  assert.match(wrongBranch.stderr, /not a branch of this repository/);
  git(repo, "branch", "other", "main");
  const offBranch = record(1, "CLEAR", { branch: "other" });
  assert.equal(offBranch.status, 1, offBranch.stdout);
  assert.match(offBranch.stderr, /is not a commit on branch other/);
  const first = record(1, "CLEAR");
  assert.equal(first.status, 0, first.stderr);
  const second = record(2, "CLEAR", { head: heads[0] });
  assert.equal(second.status, 0, second.stderr);
  assert.match(second.stdout, /VERIFY_CONVERGENCE_RECEIPT/);
});

test("a deleted state file or a fresh clone rebuilds the spent budget from committed round records", (t) => {
  const { repo, record } = recorderRepo(t);
  for (const n of [1, 2]) { assert.equal(record(n, "NOT_CLEAR").status, 0); }
  const third = record(3, "NOT_CLEAR");
  assert.equal(third.status, 2, third.stdout + third.stderr);
  git(repo, "add", "-A"); git(repo, "commit", "-qm", "round records");
  rmSync(join(repo, ".claude/learning/redteam-stall-state.json"));
  const fourth = record(4, "NOT_CLEAR");
  assert.equal(fourth.status, 2, `the cap still holds after the state file is deleted: ${fourth.stdout}${fourth.stderr}`);
  assert.match(fourth.stderr, /single debug round/);
  // No state and no committed history: a later round is refused, never counted as a first round.
  const bare = recorderRepo(t);
  const orphan = bare.record(3, "NOT_CLEAR");
  assert.equal(orphan.status, 1, orphan.stdout + orphan.stderr);
  assert.match(orphan.stderr, /a missing history is never a fresh budget/);
});

// ---- convergence receipt: identities, security lens, evidence and round records -------------

// A converged wave w01 on branch feat/w01: two clean rounds, both lenses, receipt committed.
// `tweak` edits the receipt / records / files just before the receipt commit.
function wave(t, tweak = () => {}, { securityAgent = "harness-security-reviewer" } = {}) {
  const dir = tempDir(t, "harness-wave-"), ws = "workspaces/demo", branch = "feat/w01";
  git(dir, "init", "-q", "-b", "main");
  put(dir, ".gitignore", ".claude/learning/\n");
  put(dir, `${ws}/04-validate/acceptance-w01.md`, "# Acceptance w01\nw01-01 A1: echo returns its input. Approved by Fixture Owner (synthetic).\n");
  git(dir, "add", "-A"); git(dir, "commit", "-qm", "acceptance");
  const base = git(dir, "rev-parse", "HEAD");
  git(dir, "checkout", "-qb", branch);
  put(dir, "src/echo.mjs", "export const echo = (v) => v;\n");
  put(dir, `${ws}/todos/completed/w01-01-echo.md`, "# w01-01\n\n## Verification\n\nBrowser walk: not applicable — command-line fixture.\n");
  git(dir, "add", "-A"); git(dir, "commit", "-qm", "work");
  const head = git(dir, "rev-parse", "HEAD");
  const receipt = { ...template("w01"), project: "demo", branch, wave_base: base, verdict_head: head,
    verdict_at: "2026-10-07T02:00:00Z", todos: ["todos/completed/w01-01-echo.md"],
    acceptance_list: { path: "04-validate/acceptance-w01.md", ratified_by: "Fixture Owner" },
    journal: "journal/0001-DECISION-w01.md", rounds: [] };
  const launches = [];
  for (let n = 1; n <= 2; n++) {
    const reviewers = ["correctness", "security"].map((lens) => {
      const agent = lens === "security" ? securityAgent : "harness-reviewer";
      const launch_id = `fixture-${n}-${lens}`;
      launches.push({ kind: "launch", launch_id, subagent_type: agent, ts: "2026-10-07T01:00:00Z" });
      const evidence = `${ws}/04-validate/w01-${lens}-r${n}.md`;
      put(dir, evidence, `Synthetic fixture report.\nVerdict: CLEAR\nCommit: ${head}\n`);
      return { agent, lens, ran: true, evidence, launch_id };
    });
    put(dir, `${ws}/04-validate/round-w01-${n}.json`, JSON.stringify({ branch, round: n, head, expected_reviewers: ["correctness", "security"],
      reviewers: reviewers.map((r) => ({ id: r.lens, verdict: "CLEAR", evidence: r.evidence })), root_causes: [] }));
    put(dir, `${ws}/${receipt.launches}`, launches.map((x) => JSON.stringify(x)).join("\n") + "\n");
    git(dir, "add", "-A"); git(dir, "commit", "-qm", `dispatch ${n}`);
    receipt.rounds.push({ n, head, clean: true, new_gating_findings: 0, reviewers });
  }
  put(dir, `${ws}/${receipt.journal}`, "# w01 converged (synthetic fixture)\n");
  tweak({ dir, ws, receipt, head, put: (p, c) => put(dir, p, c), rm: (p) => unlinkSync(join(dir, p)) });
  put(dir, `${ws}/04-validate/convergence-w01.json`, JSON.stringify(receipt));
  git(dir, "add", "-A"); git(dir, "commit", "-qm", "receipt");
  return node([join(root, ".harness/bin/check-redteam-convergence-receipt.mjs"), "--workspace", resolve(dir, ws), "--scope", "w01"], { cwd: dir });
}

test("convergence receipt control: the honest fixture converges", (t) => {
  const ok = wave(t);
  assert.equal(ok.status, 0, ok.stdout + ok.stderr);
});

test("convergence receipt refuses agent identities as acceptors and a relabelled security lens", (t) => {
  for (const who of ["codex", "security-reviewer", "harness-reviewer", "independent planning reviewer"]) {
    const result = wave(t, ({ receipt }) => { receipt.acceptance_list.ratified_by = who; });
    assert.equal(result.status, 1, who);
    assert.match(result.stdout, /acceptance-self-authored/, who);
  }
  const residual = wave(t, ({ receipt }) => {
    receipt.residuals = [{ finding: "x", category: "INCREMENTAL", accepted_by: "harness-security-reviewer", blocking_safety_note: "n",
      value_anchor: "v", full_fix_criteria: "c", revisit_trigger: "r", backstop: "2026-12-31" }];
  });
  assert.equal(residual.status, 1);
  assert.match(residual.stdout, /residual-unaccepted/);
  const relabelled = wave(t, () => {}, { securityAgent: "harness-reviewer" });
  assert.equal(relabelled.status, 1, relabelled.stdout);
  assert.match(relabelled.stdout, /security-lens-not-specialist/);
});

test("convergence receipt ties every round to a saved report and a matching committed round record", (t) => {
  const cases = [
    ["free-text evidence", ({ receipt }) => { receipt.rounds[1].reviewers[0].evidence = "trust me"; }, /reviewer-evidence-not-a-report/],
    ["evidence never saved", ({ receipt, ws }) => { receipt.rounds[1].reviewers[0].evidence = `${ws}/04-validate/w01-correctness-r9.md`; }, /reviewer-evidence-missing/],
    ["evidence is a directory", ({ ws, receipt, put: p }) => {
      p(`${ws}/04-validate/reports/w01-correctness-r2.md`, "Verdict: CLEAR\n");
      receipt.rounds[1].reviewers[0].evidence = `${ws}/04-validate/reports`;
    }, /reviewer-evidence-missing/],
    ["evidence saved empty", ({ ws, put: p }) => { p(`${ws}/04-validate/w01-security-r2.md`, ""); }, /reviewer-evidence-missing/],
    ["round record missing", ({ ws, rm }) => { rm(`${ws}/04-validate/round-w01-1.json`); }, /round-record-missing/],
    ["record says NOT_CLEAR", ({ ws, put: p, head }) => {
      p(`${ws}/04-validate/round-w01-2.json`, JSON.stringify({ branch: "feat/w01", round: 2, head, expected_reviewers: ["correctness", "security"],
        reviewers: [{ id: "correctness", verdict: "NOT_CLEAR", evidence: `${ws}/04-validate/w01-correctness-r2.md` },
          { id: "security", verdict: "CLEAR", evidence: `${ws}/04-validate/w01-security-r2.md` }], root_causes: ["x"] }));
    }, /round-record-mismatch/],
    ["later round left out", ({ ws, put: p, head }) => {
      p(`${ws}/04-validate/round-w01-3.json`, JSON.stringify({ branch: "feat/w01", round: 3, head, expected_reviewers: ["correctness"],
        reviewers: [{ id: "correctness", verdict: "NOT_CLEAR", evidence: `${ws}/04-validate/w01-correctness-r2.md` }], root_causes: ["x"] }));
    }, /round-record-after-receipt/],
  ];
  for (const [label, tweak, expected] of cases) {
    const result = wave(t, tweak);
    assert.equal(result.status, 1, `${label}: ${result.stdout}`);
    assert.match(result.stdout, expected, label);
  }
});
